# Generated by Django 4.2.6 on 2023-10-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
