# Generated by Django 4.2.6 on 2023-10-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
