# Generated by Django 4.2.6 on 2023-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
